---
# handlers file for zabbix
- name: restart zabbix agent
  service:
    name: zabbix-agent
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: restart zabbix server
  service:
    name: zabbix-server
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: create selinux mod
  command: checkmodule -M -m -o /etc/zabbix/my-zabbixserver.mod /etc/zabbix/my-zabbixserver.te

- name: create selinux pp
  command: semodule_package -o /etc/zabbix/my-zabbixserver.pp -m /etc/zabbix/my-zabbixserver.mod

- name: load selinux pp
  command: semodule -i /etc/zabbix/my-zabbixserver.pp
    
- name: import zabbix schema
  mysql_db:
    state: import
    name: zabbix
    target: /usr/share/doc/zabbix-server-{{ zabbix_server_type}}-{{ zabbix_version_major }}.{{ zabbix_version_minor }}/create.sql.gz
    login_host: "{{ zabbix_server_database_host }}"
    login_user: "{{ zabbix_server_database_user }}"
    login_password: "{{ zabbix_server_database_pass }}"

- name: restart httpd
  service:
    name: "{{ item }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
  with_items:
    - "{{ zabbix_httpd_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(zabbix_httpd_service[ansible_distribution]
      | default(zabbix_httpd_service['default'] )) }}"
