---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: zabbix-centos-6
    box: centos/6
  - name: zabbix-centos-7
    box: centos/7
  - name: zabbix-debian-jessie64
    box: debian/jessie64
  - name: zabbix-ubuntu-trusty
    box: ubuntu/trusty64
  - name: zabbix-ubuntu-artful
    box: ubuntu/artful64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: 'None'
