---
# vars file for zabbix
zabbix_agent_service: zabbix-agent

zabbix_server_service: zabbix-server

zabbix_proxy_service: zabbix-proxy

zabbix_java_gateway_service: zabbix-java-gateway

zabbix_httpd_service: httpd
